In ApplicationForm.tsx, update progress bar based on questions answered
keepid/keepid_client pull request #126
Opened 2020-11-01 20:12 UTC by vanessa-hu

- made progressBarFill() function that calculates percent amt of questions answered based on total number of questions, to be used in the progress-bar divs in the render()
- rounds to whole number
- backtracks if input is removed
- also display percent number, can remove if needed
- realized that page numbers are just 0 out of 0? not sure if that is a bug or I just didn't pull since starting this branch

![image](https://user-images.githubusercontent.com/21111373/97813203-82124c80-1c54-11eb-8dad-694c39759259.png)

2020-11-01 21:54 UTC, crchong1 requested changes
just a couple small comments!

2020-11-01 21:54 UTC, crchong1 commented on src/components/PDF/ApplicationForm.tsx
> +  const arr = dataurl.split(','); // const mime = arr[0].match(/:(.*?);/)[1];
can we remove this commented out code?

2020-11-01 21:54 UTC, crchong1 commented on src/components/PDF/ApplicationForm.tsx
> +  progressBarFill() {
arrow function (so do progressBarFill = () => {}) and also add a type declaration. This returns an int right? so lets define the return as an int

2020-11-01 23:14 UTC, vanessa-hu commented
Done! Also didn't realize VSCode had in-house PR/Issue manager... so cool :O

2020-11-02 01:55 UTC, crchong1 approved these changes

2020-11-02 03:11 UTC, merged