Worker landing page
keepid/keepid_client pull request #370
Opened 2022-06-15 19:41 UTC by alexgtang

## Description of changes
Redesigned the worker landing page. Added cards and pagination. Can click on cards to view client profile.
## Screenshot(s) or GIF(s) of changes
<img width="889" alt="image" src="https://user-images.githubusercontent.com/102643727/173911034-bcdbe41c-11e1-451e-b605-998b864cc535.png">

2022-06-17 16:22 UTC, alexgtang commented
https://github.com/keepid/keepid_client/issues/323

2022-06-17 21:31 UTC, crchong1 commented on src/static/styles/App.scss
> +	padding: 8px 16px;
small nits but still try to convert px to rem

2022-06-17 21:32 UTC, crchong1 commented on src/static/styles/App.scss
> +	border: 1px solid #ECEEEF;
we should reuse color variables as much as possible- can you make a grey variable if it doesn't already exist

2022-06-17 21:33 UTC, crchong1 commented on src/components/LandingPages/WorkerLanding.tsx
> +          <div className="dropdown" style={{ position: 'absolute', top: 24, right: 24 }}>
if possible, lets not have in-line styling inside the html. If needed, we can define new CSS classes and have them apply to a bunch of areas at once.

2022-06-17 21:34 UTC, crchong1 requested changes
just left a couple of small css comments

2022-06-17 21:35 UTC, crchong1 commented
also can you look into why you tests are failing on circleci? that might be a bit alarming

2022-06-20 21:03 UTC, crchong1 commented
sorry one last comment- can you revert the behavior of the search bar so it will search on type?

2022-06-20 21:04 UTC, crchong1 approved these changes
Just left one last comment, otherwise lgtm

2022-06-20 21:59 UTC, alexgtang commented
Yep! The search bar now searches on type. I also gave the workers the option to just click 'Search' which will display all results.

2022-06-20 21:59 UTC, merged