Update IdCategories.tsx
keepid/keepid_client pull request #467
Opened 2022-11-08 03:31 UTC by alexgtang

## Link to Issue

https://github.com/keepid/keepid_client/issues/466

## Description of changes

Changed wording in enum

2022-11-12 22:06 UTC, mkhagan8 approved these changes
With my limited programming knowledge, it looks good to me.

2022-11-15 16:27 UTC, steffen12 commented
I think we should do "'Drivers License / Photo ID' with a space surrounding the /

2022-11-15 16:28 UTC, steffen12 requested changes

2022-11-15 16:28 UTC, steffen12 commented on src/components/Documents/IdCategories.tsx
> +  DriversLicense = 'Drivers License/Photo ID',
Change

2022-11-15 16:28 UTC, steffen12 commented on src/components/Documents/IdCategories.tsx
> +  MedicaidCard = 'Medical Insurance Card',
Good

2022-11-16 06:12 UTC, steffen12 approved these changes
Looks Good

2022-11-16 06:12 UTC, merged